/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;
import static spark.Spark.*;


public class App {
    public String getGreeting() {
        return "Hello Molly!";
    }

    public static void main(String[] args) throws Exception {
        port(5000);
        new User().addRoutes();
    }
}
 

