/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import edu.au.cc.gallery.tools.UserAdmin;

public class App {
    public String getGreeting() {
        return "Hello Molly!";
    }

    public static void main(String[] args) throws Exception {
       // System.out.println(new App().getGreeting());
       //S3.demo();
        UserAdmin.adminMenu();
	
    }
}
 
